export const CHANGE_CURRENT_SONG = "player_CHANGE_CURRENT_SONG"
export const CHANGE_PLAY_LIST = "player_CHANGE_PLAY_LIST"
export const CHANGE_CURRENT_SONG_INDEX = "player_CHANGE_CURRENT_SONG_INDEX"

export const CHANGE_PLAY_SEQUENCE = "player_CHANGE_PLAY_SEQUENCE"
export const CHANGE_LYRIC_LIST = "player_CHANGE_LYRIC_LIST"
export const CHANGE_CURRENT_LYRIC_INDEX = "player_CHANGE_CURRENT_LYRIC_INDEX"