export const CHANGE_CATEGORY = "songs_CHANGE_CATEGORY";
export const CHANGE_CURRENT_CATEGORY = "songs_CHANGE_CURRENT_CATEGORY";
export const CHANGE_CATEGORY_SONGS = "songs_CHANGE_CATEGORY_SONGS";

export const PER_PAGE_NUMBER = 35;
